### ISSUE TITLE
Codium vs. VSCodium

### ISSUE THREAD

**Issue by GitMensch** [Alex313031/codium#1]
Just happen to recognize that: While the name was changed to Codium and this stayed that way with 1.82 many references were changed to VSCODIUM during 1.82 "manual rebase".

This may or may not be an issue.

**Comment by Alex313031** [comment]
@GitMensch Like where? I tried to rebrand it correctly like when I first made the repo, but I ended up rebasing on top of upstream since there were alot of changes.

**Comment by GitMensch** [comment]
The repo is currently indexed, but https://github.com/search?q=repo%3AAlex313031%2Fcodium%20vscodium&type=code should give a clue.

**Comment by Alex313031** [comment]
@GitMensch Those are left intentionally, as they don't need to be changed. File names and the announcements patch purposefully still have vscodium name. However, I could update the docs to use the new name and make it clear that this is the (currently) only vscode/vscodium fork to still support win7/8/8.1 or ubuntu 16.04.

**Comment by GitMensch** [comment]
Just rechecked - the README is still mostly from VSCodium with instructions on how to install that one (not this fork).

> However, I could update the docs to use the new name and make it clear that this is the (currently) only vscode/vscodium fork to still support win7/8/8.1 or ubuntu 16.04.

This part is very important, as the question comes up again also for Ubuntu 18/RHEL7, as electron dropped support for that (but there are now the experimental glibc-217 node binaries, which may be used as drop-in replacement (also checked for VSCodium see https://github.com/VSCodium/vscodium/issues/1629)

**Comment by Alex313031** [comment]
@GitMensch Finished. See replies to your other issues. Should be all good now.

**Comment by GitMensch** [comment]
Flushed it it: it is much better now. But the instructions still lead to vscodium' s Gitter references.

**Comment by Alex313031** [comment]
@GitMensch Probably wont update those.

**Comment by Alex313031** [comment]
@GitMensch Went ahead and updated all this, and other stuff in the readme as well as the building instructions. Also added the wiki, but right now it's identical to upstream.

**Comment by GitMensch** [comment]
Well done. This looks all fine, the only thing you likely want to adjust is https://github.com/Alex313031/codium?tab=readme-ov-file#supported-platforms - as this is one of the core parts of this repo.

**Comment by Alex313031** [comment]
@GitMensch There > https://github.com/Alex313031/codium?tab=readme-ov-file#supported-platforms
