### ISSUE TITLE
A question and some problems

### ISSUE THREAD

**Issue by TRX99** [Alex313031/codium#17]
Hello

1. I have Windows 7 64 bit. Why is there no 64-bit version of Codium in the download list? Because the 64-bit version can use more M and its speed increases.

2. I set the workbench.startupEditor option to None in the settings section, but the Welcome page still appears. I want to disable it.

3. When I open the web pages I made earlier I keep getting this message:

![a1](https://github.com/user-attachments/assets/144782b7-e7c3-4a41-bec1-a64ada3aba5f)

4. In VSCode version 1.70.3, I don't have these problems at all, and even its opening speed is very high, but codium is a bit slow.

All these comments are for the betterment of this program. from Alex, thank you for your hard work.

Thank you

**Comment by n0099** [comment]
3. https://github.com/microsoft/vscode/issues/147888

**Comment by Alex313031** [comment]
@n0099 @TRX99 Yup. This is the answer. Codium should be faster than VSCodium, but it will definitely be slower than the 1.70.3 release, simply because of how much more has been tacked on since then.
