### ISSUE TITLE
Problem with installing Extensions

### ISSUE THREAD

**Issue by TRX99** [Alex313031/codium#19]
Hello

Thank you for the new 64-bit version.

How to install the following extension in Codium?

https://marketplace.visualstudio.com/items?itemName=Wscats.cors-browser

I want the extension above, but I search and install the extension below from inside Codium, but alt+B does not work.

https://marketplace.visualstudio.com/items?itemName=techer.open-in-browser

Thank you

**Comment by Alex313031** [comment]
@TRX99 Codium uses the open source extensions site, just like VSCodium.

For extensions that aren't on there and are only available on the proprietary Microsoft site, first, download the VSIX file for the extension. For the one you linked, heres a cropped screenshot.
![Screenshot from 2024-09-04 00-22-50](https://github.com/user-attachments/assets/eadc2e7f-5214-4909-85c2-4834bcadcd62)

Notice the "Download Extension" link.

Then, follow these instructions for manually installing an extension. This is also the same method that extension developers use to load their in-progress extensions into VSCode to test them.

https://stackoverflow.com/questions/42017617/how-to-install-vs-code-extension-manually
