### ISSUE TITLE
README doesn't match

### ISSUE THREAD

**Issue by GitMensch** [Alex313031/codium#2]
Obviously the install instructions are about VSCodium itself, not this fork.

Please recreate that also pointing out the goals/reasoning of the fork - https://github.com/VSCodium/vscodium/issues/1264#issuecomment-1729889693 - is a big one for Win (also the change that the zip files are for portable installations),

Thank you for sharing your work!

**Comment by Alex313031** [comment]
@GitMensch Yeah I can update the docs as I mentioned in comment for your other issue.

Do you use Codium on Windows 7? I do

**Comment by GitMensch** [comment]
I suggest to reopen and adjust README - all the installation instructions are for vscodium, most of the other content, too, including the dependencies as Windows 10.

**Comment by GitMensch** [comment]
Suggestion: adjust the README in a branch, this way you can mostly merge over this one commit after rebasing (you may include one or more commits for the build scripts, rebranding, ...in that branch, too).

**Comment by Alex313031** [comment]
@GitMensch I updated the readme to include info about win7 and ubuntu 18.04. I just made a 1.86.0 release, and it still builds and runs fine on 18.04 and win7.

Also minified the installing section to just point to the releases here.
