### ISSUE TITLE
TODO: patch of server check

### ISSUE THREAD

**Issue by GitMensch** [Alex313031/codium#4]
The new script [resources/server/bin/helpers/check-requirements-linux.sh](https://github.com/microsoft/vscode/pull/202210/files#diff-826d1bb62415a9f372ee0635156510fd9bcfcbdf182948f6cd15ebd214e510dc) will likely need a patch, to ne adjusted for whatever the minimal requirements for this fork are.

Note: what the exact minimal requirements are and how this makes the difference to VSCodium is still missing in https://github.com/Alex313031/codium/blob/master/README.md (which is tracked in #1 and #2 - one of those may need to be reopened):

> @Alex313031 wrote:
> > However, I could update the docs to use the new name and make it clear that this is the (currently) only vscode/vscodium fork to still support win7/8/8.1 or ubuntu 16.04.
>
> This part is very important, as the question comes up again also for Ubuntu 18/RHEL7, as electron dropped support for that (but there are now the experimental glibc-217 node binaries, which may be used as drop-in replacement (also checked for VSCodium see https://github.com/VSCodium/vscodium/issues/1629)

**Comment by Alex313031** [comment]
@GitMensch This should still work with 18.04. I build and test it in a 18.04 VM.

**Comment by GitMensch** [comment]
The point is that vscodeserver would likely not work if you don't patch that file - as this raises an error when glibc is considered to be too old.

**Comment by Alex313031** [comment]
@GitMensch They added a patch for this upstream now, and besides, I don't ship the web version, as it doesn't make sense for this fork (which is for running on older OSes)
