### ISSUE TITLE
Add macos support

### ISSUE THREAD

**Issue by k2662** [Alex313031/codium#5]
can we port this to macos?

**Comment by Alex313031** [comment]
@k2662 Yes. We got a build working yesterday. I will try to make x64 and arm64 builds next release.

**Comment by Alex313031** [comment]
@k2662 MacOS build is in the latest release >

**Comment by Alex313031** [comment]
@k2662 Added arm64 MacOS releases as well in the latest 1.87 release > https://github.com/Alex313031/codium/releases/tag/1.87.0.24061

Closing now
