### ISSUE TITLE
How to use this with SSH remote

### ISSUE THREAD

**Issue by GitMensch** [Alex313031/codium#7]
Or: Do you plan to add REH binaries?

**Comment by Alex313031** [comment]
@GitMensch Actually, everytime I build, it makes reh archives. I didn't think anyone wanted or used it, because isn't that just the web version of VSCode? Because in that case there's really no point, and Codium doesn't offer any benefit over upstream. Codium is for people who want compiler optimization, to use it on old OSes i.e. windows 7, or because they dislike the vscodium logo.

**Comment by GitMensch** [comment]
No, the REH version is needed for using SSH (or is version WSL) remote. For this the communication goes to a server with the same hash number, which is different for Codium.

**Comment by Alex313031** [comment]
@GitMensch OOOO ok. I will release the reh archives alongside them from now on. Thnx. Sorry I didn't before, I could have the whole time because it builds it as part of the whole compilation process, I just didn't think it was necessary. I never use the web version, ssh, or the tunnel introduced recently, so I didn't know anything about it.

**Comment by Alex313031** [comment]
@GitMensch Latest 1.87.2 version has REH for Linux and Windows > https://github.com/Alex313031/codium/releases/tag/1.87.2.24075

**Comment by GitMensch** [comment]
Than you. The codium_reh works on my boxes; to have that automatically installed by Open SSH Remote one can configure (=override) its setting `remote.SSH.serverDownloadUrlTemplate`
https://github.com/jeanp413/open-remote-ssh/blob/8191939de706952fa035f80a6fce0e85f85495f6/package.json#L81

But the installation would have to be done manually for now, as its install script expects it to have in gzip'd tar format, not as zip file https://github.com/jeanp413/open-remote-ssh/blob/8191939de706952fa035f80a6fce0e85f85495f6/src/serverSetup.ts#L318-L343

To ease that and allow automatic installation - can you please adjust the reh binaries to be made available as tar.gz?

**Comment by GitMensch** [comment]
Jut out of interest: your binaries include node 16.17.1; is there a plan to increase that or is that version necesary to support older environments?

**Comment by Alex313031** [comment]
@GitMensch Yeah, next release I can leave them as .tar.gz

And well, as you know this fork is using Node 16 and Electron 22 for old OS support, i.e. Windows 7/8/8.1 & Ubuntu 18.04/Debian 9.

**Comment by Alex313031** [comment]
@GitMensch How are the reh archives working for you now? I am making Linux and Windows ones, using Node 16 (same node as the Electron 22.3.27 that this fork is using)

**Comment by GitMensch** [comment]
I've tested them directly after your last update and they worked fine, only the naming schema difference to VSCodium reh binaries was creating extra effort to get the automated download working (I've opted for a manual download back then instead).
If not adjusted so far I'd suggest to use the schema from VSCodium. In any case this issue should be closed-fixed.

**Comment by Alex313031** [comment]
@vcip If you noticed, I started offering reh archives for all platforms. You can just download from my releases instead of upstream.

**Comment by GitMensch** [comment]
remote.SSH.experimental.serverBinaryName can be used to override the hash, if there's no matching REH binary.
remote.SSH.serverDownloadUrlTemplate allowsyou to swap the default VSCodium, for example to Alex' build (as they likely have a different sha you'd either have to also use that fork instead of VSCodium or again, adjust the binary server name config)

**Comment by Alex313031** [comment]
@GitMensch @vcip Turns out this is an error on my part. I don't publish the hashes for all the files.

**Comment by ecxod** [comment]
I have issues with the Remote Explorer I do not understand if this is a connected topic
When I try to connect to the Remote Workspace it simply stuck. It creates some folders and some 0byte files and then stucks for ever.

As you see it try to download a inexistent file

```
https://github.com/VSCodium/vscodium/releases/download/1.93.1.24277/vscodium-reh-linux-x64-1.93.1.24277.tar.gz
```

```
[Trace  - 16:15:32.331] Server install command stdout:
Error downloading server from https://github.com/VSCodium/vscodium/releases/download/1.93.1.24277/vscodium-reh-linux-x64-1.93.1.24277.tar.gz
3b8e7aa9ba8bf4478c7e7c2f: start
exitCode==1==
listeningOn====
connectionToken====
logFile==/home/christian/.codium-server/.adc83b19e793491b1c6ea0fd8b46cd9f32e592fc.log==
osReleaseId==devuan==
arch==x86_64==
platform==linux==
tmpDir==/run/user/1019==
3b8e7aa9ba8bf4478c7e7c2f: end


[Error  - 16:15:32.332] Error resolving authority
Error: Couldn't install vscode server on remote server, install script returned non-zero exit status
	at t.installCodeServer (c:\Users\Christian\._codium\extensions\jeanp413.open-remote-ssh-0.0.48-universal\out\extension.js:1:441548)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async c:\Users\Christian\._codium\extensions\jeanp413.open-remote-ssh-0.0.48-universal\out\extension.js:1:404966
```
