### ISSUE TITLE
Graphical glitch when scrolling code down?

### ISSUE THREAD

**Issue by spacedrone404** [Alex313031/codium#9]
First couple of lines stay fixed at the top.
Better to describe such behavior as if position of those lines was fixed by CSS property.
Is there any way to get rid of it?

Here is screenshot.
![Untitled](https://github.com/Alex313031/codium/assets/81930707/7373e23e-6d70-4c98-96c9-8ea7496ae0bd)

I'm running Windows 7 x64 Pro ESU.

**Comment by n0099** [comment]
https://code.visualstudio.com/docs/getstarted/userinterface#_sticky-scroll

**Comment by spacedrone404** [comment]
Thanks a lot, you cleared things up!
